
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fesa.ico.compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 4;
  public static final int FROM = 3;
  public static final int CS = 8;
  public static final int SELECT = 2;
  public static final int PYC = 7;
  public static final int IGUAL = 17;
  public static final int ALL = 16;
  public static final int ID = 21;
  public static final int MEN = 18;
  public static final int COMA = 11;
  public static final int INSERT = 12;
  public static final int EOF = 0;
  public static final int VALUES = 14;
  public static final int DISTINCT = 15;
  public static final int error = 1;
  public static final int PC = 10;
  public static final int MAY = 19;
  public static final int PA = 9;
  public static final int DELETE = 6;
  public static final int COUNT = 5;
  public static final int INTO = 13;
  public static final int DIG = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "FROM",
  "WHERE",
  "COUNT",
  "DELETE",
  "PYC",
  "CS",
  "PA",
  "PC",
  "COMA",
  "INSERT",
  "INTO",
  "VALUES",
  "DISTINCT",
  "ALL",
  "IGUAL",
  "MEN",
  "MAY",
  "DIG",
  "ID"
  };
}

